[package]
name = "advent"
version = "0.1.0"
authors = ["Lincoln Quirk <lincolnq@gmail.com>"]

[dependencies]
nom = "4.1.1"
ndarray = "0.12.1"
chrono = "0.4.6"
itertools = "0.8.0"
ordered-float = "1.0.1"

